import { QinFilesNature, QinFilesOperation, QinFilesDescriptor } from "qinpel-res";
import { QinEdit } from "./qin-edit";
import { QinColumn } from "./qin-column";
import { QinExplorer } from "./qin-explorer";
import { QinLine } from "./qin-line";
import { QinString } from "./qin-string";
import { QinCombo } from "./qin-combo";
import { QinButton } from "./qin-button";
import { QinPanel } from "./qin-panel";
export declare class QinChooser extends QinEdit {
    private _qinMain;
    private _qinUpper;
    private _qinConfirm;
    private _qinName;
    private _qinExtensions;
    private _qinSearch;
    private _qinUnder;
    private _qinExplorer;
    private _nature;
    private _operation;
    private _descriptors;
    constructor(nature?: QinFilesNature, operation?: QinFilesOperation, descriptors?: QinFilesDescriptor[]);
    private initMain;
    private initUpper;
    private initUnder;
    private initExtensions;
    getMain(): HTMLDivElement;
    getData(): string[];
    setData(data: string[]): void;
    get qinMain(): QinColumn;
    get qinUpper(): QinLine;
    get qinConfirm(): QinButton;
    get qinName(): QinString;
    get qinExtensions(): QinCombo;
    get qinSearch(): QinButton;
    get qinUnder(): QinPanel;
    get qinExplorer(): QinExplorer;
    get nature(): QinFilesNature;
    get operation(): QinFilesOperation;
    get descriptors(): QinFilesDescriptor[];
}
//# sourceMappingURL=qin-chooser.d.ts.map